### ISSUE TITLE
xrdataset.CFJSONinterface dimensionless variable / shape=[] broken

### ISSUE THREAD

**Issue by aportagain** [metocean/cf-json#20]
The 0.2 (-ish? might be missing some minor increment update there?) spec says "A variable can have no dimensions if it has only a single numeric or string value, in which case the shape should be specified as []." https://github.com/cf-json/cf-json.github.io/blob/e6f18cb38aef80dd953465161df6e8cd31fe83ea/specification.md

But somehow this isn't working, either on the from_json or json_dumps or both:

```
>>> import xarray as xr
>>> from cfjson.xrdataset import CFJSONinterface
>>> ds = xr.Dataset()
>>> ds['foo'] = ([], 1)
>>> js = ds.cfjson.json_dumps()
>>> print(js)
{
  "dimensions": {},
  "attributes": {},
  "variables": {
    "foo": {
      "attributes": {},
      "data": [
        1
      ]
    }
  }
}
>>> ds2 = xr.Dataset()
>>> ds2.cfjson.from_json(js)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/source/cf-json/cfjson/xrdataset.py", line 146, in from_json
    self._obj[varname] = (var['shape'], var['data'])
KeyError: 'shape'
>>> 
```

**Comment by aportagain** [comment]
Something like this might work:

```
diff --git a/cfjson/xrdataset.py b/cfjson/xrdataset.py
index e1702af..ab3851d 100644
--- a/cfjson/xrdataset.py
+++ b/cfjson/xrdataset.py
@@ -58,7 +58,10 @@ class CFJSONinterface(object):
                 vardims=[d for d in self._obj.variables[var].dims if d in res['dimensions']]
                 varout=mapping.get(var,var)
                 res['variables'][varout]={'attributes':OrderedDict()}
-                if len(vardims):res['variables'][varout]['shape']=vardims
+                if vardims:
+                    res['variables'][varout]['shape'] = vardims
+                else:
+                    res['variables'][varout]['shape'] = []
                 for att in self._obj.variables[var].attrs:
                     if att not in SPECIAL_ATTRS:
                         newatt=self._obj.variables[var].attrs[att]
@@ -143,7 +146,10 @@ class CFJSONinterface(object):
                 self._obj[varname].attrs = var['attributes']
                 self._obj[varname].attrs['units'] = 'Python datetime64 objects'
             else:
-                self._obj[varname] = (var['shape'], var['data'])
+                if var['shape']:
+                    self._obj[varname] = (var['shape'], var['data'])
+                else:
+                    self._obj[varname] = (var['shape'], var['data'][0])
                 logging.debug('copying variable "{}" attributes: {}'.format(varname, var['attributes'].items()))
                 # Some cases result in a dtype=object array with None elements,
                 # but if this is just due to a mix of "null" and numeric values,
```

**Comment by aportagain** [comment]
Commited fix, wrote at least one round-trip test for it, works in my specific case and looks good enough for now...
